import { forwardRef } from 'react'

const COLORS = ['#38bdf8', '#818cf8', '#fbbf24', '#fb7185', '#a78bfa', '#34d399']

const formatCurrency = (num) =>
  `₹${Number(num || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

// Convert percentage-based category data into SVG pie slice paths
function buildPieSlices(categoryData, radius = 65, cx = 65, cy = 65) {
  let cumulativeAngle = -90 // start at top
  return categoryData.map((item, i) => {
    const angle = (item.percentage / 100) * 360
    const startAngle = cumulativeAngle
    const endAngle = cumulativeAngle + angle
    cumulativeAngle = endAngle

    const startRad = (startAngle * Math.PI) / 180
    const endRad = (endAngle * Math.PI) / 180

    const x1 = cx + radius * Math.cos(startRad)
    const y1 = cy + radius * Math.sin(startRad)
    const x2 = cx + radius * Math.cos(endRad)
    const y2 = cy + radius * Math.sin(endRad)

    const largeArc = angle > 180 ? 1 : 0

    const path = `M ${cx} ${cy} L ${x1} ${y1} A ${radius} ${radius} 0 ${largeArc} 1 ${x2} ${y2} Z`

    return { path, color: COLORS[i % COLORS.length], key: item.category }
  })
}

const ShareSummaryCard = forwardRef(({ totalSpent, highestCategory, categoryData, currentMonthSpending, currentMonthName }, ref) => {
  const slices = buildPieSlices(categoryData)

  return (
    <div
      ref={ref}
      style={{
        width: 500,
        padding: 40,
        background: 'linear-gradient(160deg, #020617 0%, #0f172a 100%)',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        color: '#f1f5f9',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 32 }}>
        <div style={{
          width: 36, height: 36, borderRadius: 10,
          background: '#38bdf8', display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 18
        }}>
          💰
        </div>
        <span style={{ fontSize: 20, fontWeight: 700 }}>FINO AI</span>
      </div>

      <p style={{ fontSize: 13, color: '#94a3b8', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 4 }}>
        {currentMonthName} Spending Summary
      </p>

      {/* Total */}
      <p style={{ fontSize: 42, fontWeight: 800, margin: '8px 0 24px', color: '#38bdf8' }}>
        {formatCurrency(totalSpent)}
      </p>

      {/* Pie + breakdown */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 28, marginBottom: 28 }}>
        <svg width={130} height={130} viewBox="0 0 130 130" style={{ flexShrink: 0 }}>
          {slices.map((slice) => (
            <path key={slice.key} d={slice.path} fill={slice.color} />
          ))}
          <circle cx={65} cy={65} r={30} fill="#0f172a" />
        </svg>
        <div style={{ flex: 1 }}>
          {categoryData.slice(0, 5).map((item, i) => (
            <div key={item.category} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
              <div style={{ width: 10, height: 10, borderRadius: '50%', background: COLORS[i % COLORS.length], flexShrink: 0 }} />
              <span style={{ fontSize: 13, color: '#cbd5e1' }}>{item.category}</span>
              <span style={{ fontSize: 13, color: '#64748b', marginLeft: 'auto' }}>{item.percentage}%</span>
            </div>
          ))}
        </div>
      </div>

      {/* Stat row */}
      <div style={{ display: 'flex', gap: 16, borderTop: '1px solid #1e293b', paddingTop: 20 }}>
        <div style={{ flex: 1 }}>
          <p style={{ fontSize: 11, color: '#64748b', textTransform: 'uppercase', marginBottom: 4 }}>Top Category</p>
          <p style={{ fontSize: 16, fontWeight: 700 }}>{highestCategory ? highestCategory.category : '—'}</p>
        </div>
        <div style={{ flex: 1 }}>
          <p style={{ fontSize: 11, color: '#64748b', textTransform: 'uppercase', marginBottom: 4 }}>This Month</p>
          <p style={{ fontSize: 16, fontWeight: 700 }}>{formatCurrency(currentMonthSpending)}</p>
        </div>
      </div>

      <p style={{ fontSize: 11, color: '#475569', marginTop: 28, textAlign: 'center' }}>
        Generated by FINO AI — Smart Expense Tracking
      </p>
    </div>
  )
})

ShareSummaryCard.displayName = 'ShareSummaryCard'
export default ShareSummaryCard